version: '3'
volumes:
  db:
    driver: local
networks:
    laravel_network:
        driver: bridge
services:
    app:
        container_name: laravel_app
        image: laravel_app
        restart: always
        build:
            context: ./docker
        working_dir: /var/www
        ports:
            - '9001:9000'
        volumes:
            - ./:/var/www
        networks:
            - laravel_network
    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: always
        volumes:
            - ./:/var/www
            - ./docker/nginx/logs/:/var/log/nginx/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        tty: true
        ports:
            - '8081:80'
        networks:
            - laravel_network
    cache:
        container_name: laravel_redis
        restart: always
        image: redis:alpine
        networks:
            - laravel_network
    mysql:
        container_name: laravel_mysql
        restart: always
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        networks:
            - laravel_network
        ports:
            - '3390:3306'
        volumes:
            - db:/var/lib/mysql
    worker:
      container_name: laravel_worker
      image: laravel_worker
      networks:
        - laravel_network
      restart: always
      build:
        context: ./docker/worker
      working_dir: /var/www
      volumes:
        - ./:/var/www